In [82]:
import numpy as np

In [83]:
x = np.asmatrix([1,1,0.25,0.25])

theta1 = np.asmatrix([[.5,0,-.5,.5],[-.5,.5,-.5,0],[.5,-.5,0,.5]])
theta2 = np.asmatrix([[-.5,.5,-.5,.5],[.5,0,-.5,.5],[-.5,-.5,.5,0],[.5,.5,0,-.5]])

x

matrix([[1.  , 1.  , 0.25, 0.25]])

In [84]:
z1 = theta1*x.T
z1 = np.r_[[[np.inf]], z1]
z1

matrix([[   inf],
        [ 0.5  ],
        [-0.125],
        [ 0.125]])

In [85]:
def f(z):
    return 1/(1+np.exp(-z))

In [86]:
y1 = f(z1)
y1

matrix([[1.        ],
        [0.62245933],
        [0.46879063],
        [0.53120937]])

In [87]:
z2 = theta2 * y1
z2

matrix([[-0.15756096],
        [ 0.53120937],
        [-0.57683435],
        [ 0.54562498]])

In [88]:
y2 = f(z2)
y2

matrix([[0.46069105],
        [0.62976513],
        [0.35966133],
        [0.63311996]])

In [89]:
y = np.asmatrix([1,0,0,0]).T

J = 0.5* np.sum(np.square(y - y2))
J

0.6088277137928078

In [90]:
def f_diff(z):
    return np.exp(-z)/np.square((1+np.exp(-z)))

In [91]:
np.asarray(z2).flatten()

array([-0.15756096,  0.53120937, -0.57683435,  0.54562498])

In [92]:
diag2 = np.diag(f_diff(np.asarray(z2).flatten()))
diag2

array([[0.24845481, 0.        , 0.        , 0.        ],
       [0.        , 0.23316101, 0.        , 0.        ],
       [0.        , 0.        , 0.23030506, 0.        ],
       [0.        , 0.        , 0.        , 0.23227908]])

In [93]:
delta2 = diag2 * (y-y2)
delta2

matrix([[ 0.1339939 ],
        [-0.14683667],
        [-0.08283182],
        [-0.14706052]])

In [94]:
diag1 = np.diag(f_diff(np.asarray(z1).flatten()))
diag1

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.23500371, 0.        , 0.        ],
       [0.        , 0.        , 0.24902598, 0.        ],
       [0.        , 0.        , 0.        , 0.24902598]])

In [105]:
delta1 = diag1 * theta2.T * delta2
delta1 = delta1[1:]
delta1

matrix([[ 0.00819754],
        [-0.00871455],
        [ 0.01671185]])

In [96]:
mu = 1

In [106]:
d_theta2 = mu * delta2 * y1.T
d_theta2

matrix([[ 0.1339939 ,  0.08340575,  0.06281508,  0.07117882],
        [-0.14683667, -0.09139986, -0.06883566, -0.07800102],
        [-0.08283182, -0.05155944, -0.03883078, -0.04400104],
        [-0.14706052, -0.09153919, -0.06894059, -0.07811993]])

In [107]:
d_theta1 = mu * delta1 * x
d_theta1

matrix([[ 0.00819754,  0.00819754,  0.00204939,  0.00204939],
        [-0.00871455, -0.00871455, -0.00217864, -0.00217864],
        [ 0.01671185,  0.01671185,  0.00417796,  0.00417796]])

In [109]:
theta2_new = theta2 + d_theta2
theta2_new

matrix([[-0.3660061 ,  0.58340575, -0.43718492,  0.57117882],
        [ 0.35316333, -0.09139986, -0.56883566,  0.42199898],
        [-0.58283182, -0.55155944,  0.46116922, -0.04400104],
        [ 0.35293948,  0.40846081, -0.06894059, -0.57811993]])

In [108]:
theta1_new = theta1 + d_theta1
theta1_new

matrix([[ 0.50819754,  0.00819754, -0.49795061,  0.50204939],
        [-0.50871455,  0.49128545, -0.50217864, -0.00217864],
        [ 0.51671185, -0.48328815,  0.00417796,  0.50417796]])